# Phần 1: Giới thiệu Numpy

## 1.1. Cơ bản về Numpy

In [1]:
import numpy as np
print(np.__version__)
np.set_printoptions(precision=3) # chỉ in 3 số thập phân
np.set_printoptions(threshold=20)# chỉ in tối đa 20 phần tử
np.set_printoptions(suppress=True) # không dùng scientific notation

1.19.5


In [41]:
np.set_printoptions(precision=3, suppress=True)
print(np.float(1.123456789))

1.123456789


In [48]:
np.set_printoptions(precision=7, suppress=True)
print(np.array([0.000000123456789]))

[0.0000001]


## 1.2. Tạo đối tượng dữ liệu trong Numpy 

In [2]:
# Khởi tạo mảng 1 chiều
a = [1,2,3]
print(a)

b = np.array([1,2,3])
print(b)

c = list(b)
print(c)

[1, 2, 3]
[1 2 3]
[1, 2, 3]


In [5]:
# Khởi tạo mảng 2 chiều
d = np.array([[4,5,6],[7,8,9]])
print(d)

[[4 5 6]
 [7 8 9]]


In [6]:
# Khởi tạo 1 mảng rỗng
a = np.ndarray(shape=[2,3])
print(a)
print(type(a))
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
float64


In [4]:
# Khởi tạo bằng np.array và thực hiện ép kiểu
b = np.array([[4,5,6],[7,8,9]]).astype(np.float32)
print(b)
print(type(b))
print(b.dtype)

[[4. 5. 6.]
 [7. 8. 9.]]
<class 'numpy.ndarray'>
float32


In [7]:
# Khởi tạo bằng np.asarray và thực hiện ép kiểu
b = np.asarray([[4,5,6],[7,8,9]]).astype(np.float32)
print(b)
print(type(b))
print(b.dtype)

[[4. 5. 6.]
 [7. 8. 9.]]
<class 'numpy.ndarray'>
float32


In [8]:
# So sánh khởi tạo bằng asarray và array 
a = np.array([1,2,3])
b = np.asarray(a)
c = np.array(a)
print(b is a)
print(c is a)

True
False


In [11]:
b[0] = 5
c[2] = 7
print(a)
print(b)
print(c)

[5 2 3]
[5 2 3]
[1 2 7]


### Một số hàm tạo ndarray đặc biệt

In [12]:
a = np.full([4,3], 10)
print(a)

[[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]]


In [13]:
# Tạo một dãy các số thực cách đều nhau
a = np.linspace(start=5, stop=9, num=10)
print(a)

[5.    5.444 5.889 6.333 6.778 7.222 7.667 8.111 8.556 9.   ]


In [16]:
a = np.linspace(2,5)
print(len(a))

50


In [ ]:
# Tạo một chuỗi các số giống hàm range()
a = np.arange(start=5, stop=9, step=0.5, dtype=np.float32)
print(a)

In [18]:
# Có thể không cần start và step
a = np.arange(9, dtype=np.int)
print(a)

[0 1 2 3 4 5 6 7 8]


**Hàm random**

In [49]:
# Tạo ra 1 số thực ngẫu nhiên (từ 0-1)
a = np.random.random()
print(a)
b = np.random.rand()
print(b)

0.4553304470805122
0.05183928307335872


In [53]:
# Tạo ra mảng số thực ngẫu nhiên (từ 0-1)
#np.random.seed(1)
a = np.random.random(size=(2,3,4))
print(a)

[[[0.417022  0.7203245 0.0001144 0.3023326]
  [0.1467559 0.0923386 0.1862602 0.3455607]
  [0.3967675 0.5388167 0.4191945 0.6852195]]

 [[0.2044522 0.8781174 0.0273876 0.6704675]
  [0.4173048 0.5586898 0.1403869 0.1981015]
  [0.8007446 0.9682616 0.3134242 0.6923226]]]


In [54]:
#np.random.seed(1)
b = np.random.rand(2,3,4)
print(b)

[[[0.417022  0.7203245 0.0001144 0.3023326]
  [0.1467559 0.0923386 0.1862602 0.3455607]
  [0.3967675 0.5388167 0.4191945 0.6852195]]

 [[0.2044522 0.8781174 0.0273876 0.6704675]
  [0.4173048 0.5586898 0.1403869 0.1981015]
  [0.8007446 0.9682616 0.3134242 0.6923226]]]


In [55]:
# Tạo ra 1/mảng số nguyên ngẫu nhiên
a = np.random.randint(1,10, size=(2,3)) # low=1, high=10
print(a)
b = np.random.randint(1, 5+1) # low=1, high=5
print(b)
b = np.random.random_integers(5) # low=1, high=5
print(b)

[[2 1 2]
 [9 9 4]]
3
2


<ipython-input-55-ad4f13ca5afa>:6: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  b = np.random.random_integers(5) # low=1, high=5


In [56]:
# Tạo ra mảng số thực ngẫu nhiên theo phân bố
# Phân bố chuẩn
a = np.random.normal(10.0, 2.0, 20) # mean = 10, std=2
print(a)
# Phân bố đều
b = np.random.uniform(1.0, 10.0, 20) # low=1, high=10
print(b)

[11.8631163 13.4138699  8.2161725 13.4711931  8.7377833  8.1853133
 10.7495039  9.0532345  9.0909584  9.8293239 13.0063768 12.3212822
  9.0341172  6.386742   8.1691048  9.860532   8.3000905 10.1012465
 11.4101448  6.6401161]
[6.0932082 6.5254449 9.6088209 3.3488108 3.0791388 5.8010364 9.5494432
 5.4375363 5.8654046 7.8893659 1.4081116 2.2596951 8.1316323 1.2682122
 8.9481293 5.8670937 5.0318216 9.0292228 4.3982591 5.8458222]


**Dữ liệu có cấu trúc**

In [57]:
#new_type = [('name','S10'), ('age',int)]
#values = [('Nam', 23), ('Lan', 25), ('Mai', 30)]
new_type = [('name',np.unicode_,8), ('age',int)] #utf-8, utf-16
values = [('Hoàng', 23), ('Chiến', 25), ('Mai', 30)]

a = np.array(values, dtype=new_type)
print(a)

[('Hoàng', 23) ('Chiến', 25) ('Mai', 30)]


In [58]:
# Không hoạt động với thành phần cũng là list
new_type = [('name',np.unicode_,8), ('age',int)] #utf-8, utf-16
values = [['Hoàng', 23], ['Chiến', 25], ['Mai', 30]]

a = np.array(values, dtype=new_type)
print(a)

ValueError: invalid literal for int() with base 10: 'Hoàng'

### So sánh kích thước kiểu dữ liệu với numpy

In [ ]:
# Dùng hàm sys.getsizeof để lấy kích thước của đối tượng trên RAM
import sys 
a = 13
print(type(a), sys.getsizeof(a))

In [59]:
b = [1,2,3]*1000
print(type(b), sys.getsizeof(b))

<class 'int'> 28
<class 'list'> 24056


In [61]:
# So sánh kích thước list với mảng trên RAM
b = [1,2,3]*1000
print(type(b), sys.getsizeof(b))

<class 'list'> 24056


In [62]:
c = np.array(b).astype(np.int32)
print(type(c), sys.getsizeof(c))

<class 'numpy.ndarray'> 12096


In [63]:
# Kiểm tra kích thước khi mảng và thành phần mảng bị đổi sang đối tượng Python
b = np.array([3,4], dtype=np.float64)
print(b)
print(b.size, b.itemsize, b.nbytes)
print(sys.getsizeof(b))
print(sys.getsizeof(b[0]))

[3. 4.]
2 8 16
112
32


## 1.3. Dimensions và Shapes

In [64]:
# Kiểm tra số chiều, shape, kích thước
# Thiết lập seed để mỗi lần random vẫn ra các số cũ
np.random.seed(100000) 

a = np.random.random(size=(2,3,4))
print(a)
print(a.ndim)
print(a.shape)
print(a.size, np.size(a))

[[[0.2875609 0.5082482 0.498041  0.7816695]
  [0.1224035 0.2898574 0.0271845 0.5669873]
  [0.4684055 0.4892015 0.9117266 0.6411635]]

 [[0.40222   0.0871942 0.7059167 0.4355212]
  [0.2212792 0.8095352 0.645391  0.4484552]
  [0.9796147 0.2224898 0.4249429 0.3725055]]]
3
(2, 3, 4)
24 24


In [65]:
# Truy cập phần tử trong mảng 2 chiều
np.random.seed(100000) 
a = np.random.random(size=(2,4))
print(a)
print(a[1,2])

[[0.2875609 0.5082482 0.498041  0.7816695]
 [0.1224035 0.2898574 0.0271845 0.5669873]]
0.027184512861676335
[0.5082482 0.498041  0.1224035]


In [66]:
# Truy cập phần tử trong mảng nhiều chiều
np.random.seed(100000) 
a = np.random.random(size=(2,3,4))
print(a)
print(a[0,0,1])
print(a[1,2,0])

[[[0.2875609 0.5082482 0.498041  0.7816695]
  [0.1224035 0.2898574 0.0271845 0.5669873]
  [0.4684055 0.4892015 0.9117266 0.6411635]]

 [[0.40222   0.0871942 0.7059167 0.4355212]
  [0.2212792 0.8095352 0.645391  0.4484552]
  [0.9796147 0.2224898 0.4249429 0.3725055]]]
0.5082481908477833
0.9796147047787436


**Truy cập theo cách tự lặp** (ít dùng)

In [67]:
# Truy cập phần tử trong mảng nhiều chiều 
print(a[[0,0,1],[1,2,0]])
# 1. Lấy theo chiều 0 ba lần theo [0,0,1]
# 2. Lấy theo chiều 1 ba lần theo [1,2,0]

[[0.1224035 0.2898574 0.0271845 0.5669873]
 [0.4684055 0.4892015 0.9117266 0.6411635]
 [0.40222   0.0871942 0.7059167 0.4355212]]


**Mảng có nhiều chiều có độ lớn bằng 1**

In [69]:
a = np.array([[[1,2]]])

print(a)
print(a.shape, "\n")

# Dùng hàm squeeze() để bỏ hết các chiều có size 1
print(a.squeeze())

[[[1 2]]]
(1, 1, 2) 

[1 2]


# Phần 2: Một số thao tác thông dụng

## 2.1. Các phép toán cơ bản

In [70]:
# Phép cộng và broadcasting
a = np.full(shape=(3,5), fill_value=3)
b = np.arange(5)
print(a)
print(b)

c = a+b # Cộng mảng 2 chiều và mảng 1 chiều
print(c)

d = a+1 # Cộng mảng 2 chiều và một gía trị
print(d)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]
[0 1 2 3 4]
[[3 4 5 6 7]
 [3 4 5 6 7]
 [3 4 5 6 7]]
[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


In [71]:
# Phép chia và broadcasting
c = a/b # Numpy cho phép chia 0 nhưng cảnh báo
print(c)

d = a/1.5 # Chia mảng 2 chiều cho một gía trị
print(d)

[[ inf 3.   1.5  1.   0.75]
 [ inf 3.   1.5  1.   0.75]
 [ inf 3.   1.5  1.   0.75]]
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


<ipython-input-71-cc6d8de94840>:2: RuntimeWarning: divide by zero encountered in true_divide
  c = a/b # Numpy cho phép chia 0 nhưng cảnh báo


In [72]:
# Tính tổng khi có giá trị inf hoặc nan
tong_c = np.sum(c)
print(tong_c)

c[np.isinf(c)] = np.nan
tong_c = np.sum(c)
print(tong_c)

tong_c = np.nansum(c)
print(tong_c)

inf
nan
18.75


In [73]:
# Tính tích tất cả các giá trị trong mảng
a = np.array([[4,2],[2,3]])
print(np.prod(a))

48


In [74]:
# Tính độ sai khác giữa 2 phần tử liền kề
a = np.array([20, 22, 23, 27, 21])
c = np.diff(a)
print(c)

[ 2  1  4 -6]


In [75]:
# Tính độ sai khác giữa 2 phần tử liền kề
np.random.seed(1000)
a = np.random.randint(0, 20, size=(3,4))
print(a, "\n")

c = np.diff(a)
print(c,"\n")

d = np.diff(a, axis=0)
print(d)

[[19  7  0  1]
 [ 0 13  8  9]
 [ 4 13 15 10]] 

[[-12  -7   1]
 [ 13  -5   1]
 [  9   2  -5]] 

[[-19   6   8   8]
 [  4   0   7   1]]


## 2.2. Cắt/Chia-phần/Ghép mảng

In [76]:
# Cắt mảng theo chiều dọc
np.random.seed(1000)
a = np.random.randint(0, 20, size=(3,4))
print(a, "\n")
b = np.split(a, 3)
print(b)
print(b[0])
print(b[1])
print(b[2])

print(b[0].squeeze())
print(b[1].squeeze())
print(b[2].squeeze())

[[19  7  0  1]
 [ 0 13  8  9]
 [ 4 13 15 10]] 

[array([[19,  7,  0,  1]]), array([[ 0, 13,  8,  9]]), array([[ 4, 13, 15, 10]])]
[[19  7  0  1]]
[[ 0 13  8  9]]
[[ 4 13 15 10]]
[19  7  0  1]
[ 0 13  8  9]
[ 4 13 15 10]


In [77]:
# Cắt mảng theo chiều ngang
np.random.seed(1000)
a = np.random.randint(0, 20, size=(3,4))
print(a, "\n")
b = np.split(a, 2, axis=1)
print(b, "\n")
print(b[0])
print(b[1])

[[19  7  0  1]
 [ 0 13  8  9]
 [ 4 13 15 10]] 

[array([[19,  7],
       [ 0, 13],
       [ 4, 13]]), array([[ 0,  1],
       [ 8,  9],
       [15, 10]])] 

[[19  7]
 [ 0 13]
 [ 4 13]]
[[ 0  1]
 [ 8  9]
 [15 10]]


In [ ]:
# Cắt mảng theo chiều ngang
np.random.seed(1000)
a = np.random.randint(0, 20, size=(3,6))
print(a, "\n")
b = np.split(a, [1,3,4], axis=1) #Từ 0:1, 1:3, 3:4, 4:
print(b, "\n")

In [78]:
# Cắt một số cột
np.random.seed(1000)
a = np.random.randint(0, 20, size=(3,6))
print(a, "\n")
b = a[:,[1,3,4]]

print(b, "\n")

[[19  7  0  1  0 13]
 [ 8  9  4 13 15 10]
 [ 9  4 18  9 18 13]] 

[[ 7  1  0]
 [ 9 13 15]
 [ 4  9 18]] 



In [79]:
# Ghép mảng: concatenate theo chiều dọc
np.random.seed(1000)
a = np.random.randint(0, 20, size=(3,6))
b = np.random.randint(0, 20, size=6)
print(a, "\n")
print(b, "\n")
c = np.concatenate([a,[b]])
print(c)

[[19  7  0  1  0 13]
 [ 8  9  4 13 15 10]
 [ 9  4 18  9 18 13]] 

[18 10 14  5 12 11] 

[[19  7  0  1  0 13]
 [ 8  9  4 13 15 10]
 [ 9  4 18  9 18 13]
 [18 10 14  5 12 11]]


In [80]:
# Ghép mảng: concantenate theo chiều ngang
np.random.seed(1000)
a = np.random.randint(0, 20, size=(5,2))
b = np.random.randint(0, 20, size=(5,4))
print(a, "\n")
print(b, "\n")
c = np.concatenate([a,b], axis=1)
print(c)

[[19  7]
 [ 0  1]
 [ 0 13]
 [ 8  9]
 [ 4 13]] 

[[15 10  9  4]
 [18  9 18 13]
 [18 10 14  5]
 [12 11 11  0]
 [18  4  7 16]] 

[[19  7 15 10  9  4]
 [ 0  1 18  9 18 13]
 [ 0 13 18 10 14  5]
 [ 8  9 12 11 11  0]
 [ 4 13 18  4  7 16]]


## 2.3. Sắp xếp/Tìm kiếm/Đếm

### 2.3.1. Sắp xếp

In [81]:
# Hàm np.sort
ds1 = [20, 22, 23, 25, 27, 34, 23, 21, 19, 20]
ds2 = [24, 25, 24, 21, 22, 26, 18, 25, 24, 27]
ds3 = [83, 74, 64, 86, 20, 53, 48, 92, 48, 90]
ds4 = [70, 85, 90, 78, 6,  11, 31, 8,  31, 31]

ds = np.sort([ds1, ds2, ds3, ds4])
print(ds)

[[19 20 20 ... 25 27 34]
 [18 21 22 ... 25 26 27]
 [20 48 48 ... 86 90 92]
 [ 6  8 11 ... 78 85 90]]


In [82]:
# Hàm a.sort
ds1 = [20, 22, 23, 25, 27, 34, 23, 21, 19, 20]
ds = np.array(ds1)
print(ds)
ds.sort()
print(ds)

[20 22 23 25 27 34 23 21 19 20]
[19 20 20 21 22 23 23 25 27 34]


In [ ]:
# Sắp xếp theo chiều giảm dần
ds1 = [20, 22, 23, 25, 27, 34, 23, 21, 19, 20]
ds = np.sort(ds1)
#print(ds[::-1])
#print(np.flip(ds))
#print(-np.sort(-ds))

In [83]:
# Hàm np.sort
# Sắp xếp theo item giữa các danh sách với nhau (trộn)
ds1 = [20, 22, 23, 25, 27, 34, 23, 21, 19, 20]
ds2 = [24, 25, 24, 21, 22, 26, 18, 25, 24, 27]
ds3 = [83, 74, 64, 86, 20, 53, 48, 92, 48, 90]
ds4 = [70, 85, 90, 78, 6,  11, 31, 8,  31, 31]

ds = np.sort([ds1, ds2, ds3, ds4], axis=0)
print(ds)

[[20 22 23 ...  8 19 20]
 [24 25 24 ... 21 24 27]
 [70 74 64 ... 25 31 31]
 [83 85 90 ... 92 48 90]]


In [84]:
# Sort một ma trận với: 
# axis=0: các thành phần trên 1 cột được sắp xếp (hàng bị phá vỡ)
# axis=1: các thành phần trên 1 hàng được sắp xếp (cột bị phá vỡ)

ds = np.random.randint(0,20,[10,5])
print(ds)

ds_sorted = np.sort(ds, axis=1)
print(ds_sorted)

[[11 17  0 13 18]
 [ 1 11 14 15 15]
 [17  5 11 12  5]
 ...
 [13 19 14 15  9]
 [ 6 18  9  9 12]
 [19  4  8  1  3]]
[[ 0 11 13 17 18]
 [ 1 11 14 15 15]
 [ 5  5 11 12 17]
 ...
 [ 9 13 14 15 19]
 [ 6  9  9 12 18]
 [ 1  3  4  8 19]]


In [85]:
# Hàm np.argsort()
ds1 = [20, 22, 23, 25, 27, 34, 23, 21, 19, 20]
a = np.argsort(ds1)
print(a)
print([ds1[i] for i in a])

[8 0 9 7 1 2 6 3 4 5]
[19, 20, 20, 21, 22, 23, 23, 25, 27, 34]


In [86]:
# Hàm lexsort(keys)
# (Sắp xếp các danh sách cùng nhau)
ds1 = [20, 22, 23, 25, 27, 34, 23, 21, 19, 20]
ds2 = [24, 25, 24, 21, 22, 26, 18, 25, 24, 27]

# Sắp xếp theo ds2
chỉ_số_đã_sắp_xếp_theo_ds2 = np.lexsort([ds1, ds2])
print(chỉ_số_đã_sắp_xếp_theo_ds2)
for i in chỉ_số_đã_sắp_xếp_theo_ds2:
    print(ds1[i], ds2[i])

[6 3 4 8 0 2 7 1 5 9]
23 18
25 21
27 22
19 24
20 24
23 24
21 25
22 25
34 26
20 27


In [87]:
# Hàm lexsort(keys)
# (Sắp xếp các danh sách cùng nhau)
ds1 = [20, 22, 23, 25, 27, 34, 23, 21, 19, 20]
ds2 = [24, 25, 24, 21, 22, 26, 18, 25, 24, 27]
ds3 = [83, 74, 64, 86, 20, 53, 48, 92, 48, 90]
ds4 = [70, 85, 90, 78, 6,  11, 31, 8,  31, 31]

# Sắp xếp theo ds4 trước, rồi đến ds3, ds2
chỉ_số_đã_sắp_xếp_theo_ds4 = np.lexsort([ds1,ds2,ds3,ds4])
print(chỉ_số_đã_sắp_xếp_theo_ds4)
for i in chỉ_số_đã_sắp_xếp_theo_ds4:
    print(ds1[i], ds2[i], ds3[i], ds4[i])

[4 7 5 6 8 9 0 3 1 2]
27 22 20 6
21 25 92 8
34 26 53 11
23 18 48 31
19 24 48 31
20 27 90 31
20 24 83 70
25 21 86 78
22 25 74 85
23 24 64 90


In [88]:
# Sắp xếp mảng nhiều chiều bằng lexsort
# Lưu ý: hầu như không thấy dùng
ds = np.random.randint(0,20,[2,3,5,4])
print(ds)

ds_sorted = np.lexsort(ds, axis=-1)
print(ds_sorted)

[[[[13 13 13  7]
   [18  0  4 14]
   [17  5 13  1]
   [17  7  4 16]
   [ 2  0 12 11]]

  [[10 15  8  0]
   [19  0  3  3]
   [11  3  6  4]
   [ 2  4  4 18]
   [17 12 15 18]]

  [[ 3  0 12 12]
   [12 18 17 16]
   [15  8  9  1]
   [17 14 13  0]
   [ 2  2  1 10]]]


 [[[ 8  2 14 16]
   [ 1 17  1  3]
   [13 13  6 14]
   [ 4  6 12 15]
   [14  8  1 12]]

  [[19 10 13  0]
   [10 17 17  6]
   [ 9 10  5 17]
   [17 19 13  3]
   [ 9 11  0  2]]

  [[12 16  2  8]
   [12  5  3 18]
   [12  5  3  7]
   [ 3 11 13  4]
   [10 10  0 15]]]]
[[[1 0 2 3]
  [2 0 3 1]
  [2 1 0 3]
  [0 1 2 3]
  [2 1 3 0]]

 [[3 1 2 0]
  [3 0 1 2]
  [2 0 1 3]
  [3 2 0 1]
  [2 3 0 1]]

 [[2 3 0 1]
  [2 1 0 3]
  [2 1 3 0]
  [0 3 1 2]
  [2 0 1 3]]]


**Làm thế nào để sắp xếp mảng theo một cột nào đó, hoặc theo nhiều cột**

In [89]:
# Dùng argsort để tạo ra danh sách sắp xếp theo 1 cột nào đó
ds = np.random.randint(0,20,[6,4])
print(ds)

sorted_rows = np.argsort(ds[:,1])
print(sorted_rows)
print(ds[sorted_rows])

[[ 5 16  7  9]
 [ 6 19  9 10]
 [ 8 14  7 15]
 [16  2  3 19]
 [ 7  1  6 14]
 [19  4 12 18]]
[4 3 5 2 0 1]
[[ 7  1  6 14]
 [16  2  3 19]
 [19  4 12 18]
 [ 8 14  7 15]
 [ 5 16  7  9]
 [ 6 19  9 10]]


In [90]:
# Dùng lexsort để tạo ra danh sách sắp xếp theo vài cột nào đó
sorted_rows = np.lexsort((ds[:,1], ds[:,2]))
print(sorted_rows)
print(ds[sorted_rows])

[3 4 2 0 1 5]
[[16  2  3 19]
 [ 7  1  6 14]
 [ 8 14  7 15]
 [ 5 16  7  9]
 [ 6 19  9 10]
 [19  4 12 18]]


### 2.3.2. Tìm kiếm

In [91]:
ds1 = np.array([20, 22, 23, 25, 27, 34, 23, 21, 19, 20])
ds2 = np.array([24, 25, 24, 21, 22, 26, 18, 25, 24, 27])
chon = np.where(ds1<ds2, ds1, ds2)
print(chon)

[20 22 23 21 22 26 18 21 19 20]


In [92]:
# Tìm kiếm theo điều kiện với where
a = np.random.randint(0,20,10)
print(a)
b = np.where(a>=10)
print(b)

[14  3  0 16 17 14  3 15  9  4]
(array([0, 3, 4, 5, 7]),)


In [93]:
# Tìm kiếm theo điều kiện với where
a = np.random.randint(0,20,[6,4])
b = np.where(a>10)
print(a)
print("Chỉ số:", b)
print("Danh sách các phần tử thỏa đk:", a[b])
print("\n")
print([(b[0][i], b[1][i]) for i in range(b[0].size)])
print([a[b[0][i], b[1][i]] for i in range(b[0].size)])

[[ 2 17 18 19]
 [19 15  3 12]
 [ 7  6 11 13]
 [14 10 16  4]
 [ 7  7  4  9]
 [19 13  1 11]]
Chỉ số: (array([0, 0, 0, 1, 1, 1, 2, 2, 3, 3, 5, 5, 5]), array([1, 2, 3, 0, 1, 3, 2, 3, 0, 2, 0, 1, 3]))
Danh sách các phần tử thỏa đk: [17 18 19 19 15 12 11 13 14 16 19 13 11]


[(0, 1), (0, 2), (0, 3), (1, 0), (1, 1), (1, 3), (2, 2), (2, 3), (3, 0), (3, 2), (5, 0), (5, 1), (5, 3)]
[17, 18, 19, 19, 15, 12, 11, 13, 14, 16, 19, 13, 11]


In [94]:
# Truy cập nhanh
print(a[np.where(a>10)])

[17 18 19 19 15 12 11 13 14 16 19 13 11]


In [95]:
# Tìm các thành phần duy nhất trong mảng
a = np.random.randint(0,30,[6,4])
print(a)
b = np.unique(a)
print(b)

[[28  6 24 18]
 [22 26  6 12]
 [29 15 23 22]
 [24 10 19 10]
 [13 19 16  4]
 [24 10 27 28]]
[ 4  6 10 12 13 15 16 18 19 22 23 24 26 27 28 29]


In [ ]:
# Kiểm tra nếu tất cả hay bất cứ thành phần nào thỏa điều kiện
# Tất cả: all
# Bất cứ: any
a = np.random.randint(0,30,[6,4])
print(a)
print(np.any(a==28))
print(np.all(a==28))

### 2.3.3. Đếm

In [96]:
# Đếm các phần tử khác 0
np.random.seed(3)
a = np.random.randint(low=0,high=10,size=20)
print(a)
print(np.count_nonzero(a))

[8 9 3 8 8 0 5 3 9 9 5 7 6 0 4 7 8 1 6 2]
18


In [97]:
# Dùng hàm bincount để đếm số lần xuất hiện của mỗi giá trị trong bins
np.random.seed(3)
a = np.random.randint(low=0,high=10,size=20)
print(a)
b = np.bincount(a)
print(b)

[8 9 3 8 8 0 5 3 9 9 5 7 6 0 4 7 8 1 6 2]
[2 1 1 2 1 2 2 2 4 3]


In [98]:
# Lưu ý: bincount đếm cả những phần tử không xuất hiện
# nếu bin vẫn nằm trong range
np.random.seed(3)
a = np.random.randint(low=0,high=10,size=5)
print(a)
b = np.bincount(a)
print(b)

[8 9 3 8 8]
[0 0 0 1 0 0 0 0 3 1]


In [99]:
# Chỉ đếm những giá trị xuất hiện trong mảng
# Dùng np.unique với tham số return_counts=True
np.random.seed(3)
a = np.random.randint(low=0,high=10,size=20)
u,c = np.unique(a, return_counts=True)
print(u)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[2 1 1 2 1 2 2 2 4 3]


In [100]:
# Đếm số phần tử thỏa một điều kiện nào đó bằng count_nonzero
np.random.seed(3)
a = np.random.randint(low=0,high=10,size=20)
print(a)
b = np.count_nonzero(a==8)
print(b)

[8 9 3 8 8 0 5 3 9 9 5 7 6 0 4 7 8 1 6 2]
4


In [101]:
# Đếm phần tử kiểu string
a = np.array(['Tôi', 'thích', 'ăn', 'chuối,', 'ko', 'thích', 'ăn', 'sầu', 'riêng'])
print(a)
print(np.count_nonzero(a == 'ăn'))

u,c = np.unique(a, return_counts=True)
print(u)
print(c)

['Tôi' 'thích' 'ăn' 'chuối,' 'ko' 'thích' 'ăn' 'sầu' 'riêng']
2
['Tôi' 'chuối,' 'ko' 'riêng' 'sầu' 'thích' 'ăn']
[1 1 1 1 1 2 2]


In [102]:
# Tương tự như hàm count của đối tượng list
mmm = ['Tôi', 'thích', 'ăn', 'chuối,', 'ko', 'thích', 'ăn', 'sầu', 'riêng']
mmm.count('ăn')

2

## 2.4. Thay đổi chiều và hình dạng

In [103]:
# Đổi từ 1 chiều sang nhiều chiều
a = np.arange(20)
print(a)
b = a.reshape(4,5)
print(b)
c = a.reshape(2,2,5)
print(c)
d = b.reshape(2,2,5)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


In [104]:
# Đảo từ cột sang dòng và ngược lại (transpose)
print(b.T)
print(b.transpose())
print(b.swapaxes(0,1))

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [105]:
# Chuyển từ mảng nhiều chiều sang 1 chiều
ds = np.random.randint(0,20,[2,3])
print(ds)

print(np.ravel(ds))
print(ds.flatten())

[[ 2  1 19]
 [ 5  8 14]]
[ 2  1 19  5  8 14]
[ 2  1 19  5  8 14]
